name: Deploy React App to Google Cloud VM

on:
  push:
    branches:
      - master  # Trigger deployment on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GC_VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GC_VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh ${{ secrets.GC_VM_USER }}@${{ secrets.GC_VM_HOST }} << 'EOF'
            # Ensure web directory exists
            mkdir -p /home/griffinmuteti64/web
            cd /home/griffinmuteti64/web

            # Pull latest changes or clone the repo
            if [ -d ".git" ]; then
              git pull origin master
            else
              git clone git@github.com:Thegeektets/savannah-accessibility-frontend.git .
            fi

            # Update API URL in .env
            echo "REACT_APP_API_URL=http://localhost:8000/api" > .env

            # Install dependencies and build the React app
            npm install
            npm run build

            # Install Nginx if not installed
            sudo apt update
            sudo apt install -y nginx

            # Ensure Nginx default directory is clean and copy new build
            sudo rm -rf /var/www/html/*
            sudo cp -r build/* /var/www/html/

            # Set correct permissions
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html

            # Restart Nginx
            sudo systemctl restart nginx
          EOF
