name: Deploy React App to Google Cloud VM

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts || exit 1

      - name: Deploy to VM
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            set -e  # Exit on error

            # Ensure web directory exists
            mkdir -p /home/griffinmuteti64/web
            cd /home/griffinmuteti64/web

            # Clone or pull latest changes
            if [ -d ".git" ]; then
              git reset --hard
              git checkout master
              git pull origin master
            else
              git clone git@github.com:thegeektets/savannah-accessibility-frontend.git .
              git checkout master
            fi

             # Install or update NVM and use Node.js v19.1.0
            export NVM_DIR="$HOME/.nvm"
            if [ ! -d "$NVM_DIR" ]; then
              curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
              source ~/.bashrc
            fi
            source ~/.nvm/nvm.sh
            nvm install 19.1.0
            nvm use 19.1.0
            node -v  # Check Node.js version
            

            # Update API URL in .env
            echo "REACT_APP_API_URL=http://${{ secrets.VM_HOST }}/api" > .env

            # Install dependencies and build the React app
            npm install
            npm run build

            # Install Nginx if not installed
            if ! command -v nginx &> /dev/null; then
              sudo apt update
              sudo apt install -y nginx
            fi

            # Ensure Nginx default directory is clean and copy new build
            sudo rm -rf /var/www/html/*
            sudo cp -r build/* /var/www/html/

            # Set correct ownership and permissions
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html

            # Restart Nginx
            sudo systemctl restart nginx
          EOF
